name: Run tests

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  test:
    name: Test on ${{ matrix.os }} ${{ matrix.arch_name }}
    runs-on: ${{ matrix.runner }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: darwin
            rust_target: x86_64-apple-darwin
            arch_name: x64
            runner: macos-13
          - os: darwin
            rust_target: aarch64-apple-darwin
            arch_name: arm64
            runner: macos-latest
          - os: linux
            rust_target: x86_64-unknown-linux-gnu
            arch_name: x64
            runner: ubuntu-latest
          - os: linux
            rust_target: aarch64-unknown-linux-gnu
            arch_name: arm64
            runner: ubuntu-24.04-arm

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.rust_target }}

      - name: Run tests
        shell: bash
        run: make test CARGO_OPTS="--target ${{ matrix.rust_target }}"
