# frozen_string_literal: true

# This file was generated by https://github.com/petrgazarov/git-repo-name/blob/master/.github/workflows/release_packages.yml
class GitRepoName < Formula
  desc "Sync repository name between your local git repo and remote"
  homepage "https://github.com/petrgazarov/git-repo-name"
  version "${VERSION}"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "${DARWIN_X64_URL}"
      sha256 "${DARWIN_X64_SHA256}"
    end

    if Hardware::CPU.arm?
      url "${DARWIN_ARM64_URL}"
      sha256 "${DARWIN_ARM64_SHA256}"
    end

    def install
      if Hardware::CPU.intel?
        filename = File.basename("${DARWIN_X64_URL}")
        bin.install filename => "git-repo-name"
      end

      if Hardware::CPU.arm?
        filename = File.basename("${DARWIN_ARM64_URL}")
        bin.install filename => "git-repo-name"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "${LINUX_ARM64_URL}"
      sha256 "${LINUX_ARM64_SHA256}"
    end

    if Hardware::CPU.intel?
      url "${LINUX_X64_URL}"
      sha256 "${LINUX_X64_SHA256}"
    end

    def install
      if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
        filename = File.basename("${LINUX_ARM64_URL}")
        bin.install filename => "git-repo-name"
      end

      if Hardware::CPU.intel?
        filename = File.basename("${LINUX_X64_URL}")
        bin.install filename => "git-repo-name"
      end
    end
  end

  test do
    system "#{bin}/git-repo-name", "--version"
  end
end 