# frozen_string_literal: true

# This file was generated by https://github.com/petrgazarov/git-repo-name/blob/master/.github/workflows/release_packages.yml
class GitRepoName < Formula
  desc "CLI tool to sync local git directory name with remote repository name"
  homepage "https://github.com/petrgazarov/git-repo-name"
  version "${VERSION}"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "${DARWIN_X64_URL}"
      sha256 "${DARWIN_X64_SHA256}"
    end

    if Hardware::CPU.arm?
      url "${DARWIN_ARM64_URL}"
      sha256 "${DARWIN_ARM64_SHA256}"
    end

    def install
      if Hardware::CPU.intel?
        filename = File.basename("${DARWIN_X64_URL}")
        bin.install filename => "git-repo-name-bin"
      end

      if Hardware::CPU.arm?
        filename = File.basename("${DARWIN_ARM64_URL}")
        bin.install filename => "git-repo-name-bin"
      end
      
      # Install the shell wrapper
      (bin/"git-repo-name").write <<~EOS
        #!/bin/sh
        # This shell script wrapper handles directory changes when using git-repo-name
        exec /bin/sh "#{share}/git-repo-name/git-repo-name.sh" "$@"
      EOS
      
      chmod 0755, bin/"git-repo-name"
      (share/"git-repo-name").install "${SHELL_SCRIPT_PATH}" => "git-repo-name.sh"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "${LINUX_ARM64_URL}"
      sha256 "${LINUX_ARM64_SHA256}"
    end

    if Hardware::CPU.intel?
      url "${LINUX_X64_URL}"
      sha256 "${LINUX_X64_SHA256}"
    end

    def install
      if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
        filename = File.basename("${LINUX_ARM64_URL}")
        bin.install filename => "git-repo-name-bin"
      end

      if Hardware::CPU.intel?
        filename = File.basename("${LINUX_X64_URL}")
        bin.install filename => "git-repo-name-bin"
      end
      
      # Install the shell wrapper
      (bin/"git-repo-name").write <<~EOS
        #!/bin/sh
        # This shell script wrapper handles directory changes when using git-repo-name
        exec /bin/sh "#{share}/git-repo-name/git-repo-name.sh" "$@"
      EOS
      
      chmod 0755, bin/"git-repo-name"
      (share/"git-repo-name").install "${SHELL_SCRIPT_PATH}" => "git-repo-name.sh"
    end
  end

  test do
    system "#{bin}/git-repo-name", "--version"
  end
end 